model:
  name: chatgpt
  api_key: "your-api-key"
  azure_endpoint: "https://example.openai.azure.com/"
  api_version: "2024-02-01"

goals: [qed,logp,similarity]

optimization:
  pop_size: 20
  eval_budget: 200
  ngen: 10

prompt_template: "/home/v-nianran/src/MOLLM/data/.json"

dataset:
  path: "/home/v-nianran/src/MOLLM/data/uniform150_test.json"

init_datset: ZINC

save_dir: "/home/v-nianran/src/results"
save_suffix: "uniform150"
