model:
  name: chatgpt
  prompt_module: Prompt

goals: [qed,logp,donor,similarity]

optimization: 
  pop_size: 20
  eval_budget: 200
  ngen: 10

dataset:
  path: "/home/v-nianran/src/MOLLM/data/uniform150_test.json"

init_datset: ZINC

save_dir: "/home/v-nianran/src/results"
save_suffix: "uniform150"
