#exper_name: "7.4, with genetic_gfn as au model, start inserting 30 offspring in each generation after oracle calls > 0, and "
exper_name: "gpt 4o base experiments with exp"
save_dir: "/home/hp/src/mollm_results/"
save_suffix: "0708_exp"
initial_pop: "random1" # best100, worst100, random1 ~ 5

material: False
model:
  name: zgca,gpt-4o-2024-05-13  #,gemini-2.5-flash-preview-04-17-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 
use_au: False

goals: [sa,drd2,qed,gsk3b,jnk3]

optimization: 
  pop_size: 50
  eval_budget: 5000
  ngen: 5

dataset:
  path: "/home/hp/src/MOLLM/data/goals5.json"

init_datset: ZINC



