#exper_name: "abandon outdate experience, best f 0.5, pareto 0.25, hvc0.25, use molecules and experience, wo description, describe total value, add a sentence avoid"
#exper_name: "0.5 exp, add a sentence in crossover, experience with best_f 0.5, pareto 0.5, with description, and other description in above,cycle_length = 10
#         experience use random best 10 from best 100
#         remove good molecules history in explore prompt
#         0.5 pareto selection and 0.5 hvc selection"
exper_name: "6 objectives"
save_dir: "/home/msrai4srl4s/nian/results/6obj"
save_suffix: "0124__0820"
initial_pop: "random1" # best100, worst100, random1 ~ 5

material: False
model:
  name: chatgpt
  prompt_module: Prompt
  experience_prob: 0.
  crossover_prob: 0.8
  mutation_prob: 0.2 #0.25
  explore_prob: 0. #0.25


goals: [sa,drd2,qed,gsk3b,jnk3,bbbp]

optimization: 
  pop_size: 50
  eval_budget: 5000
  ngen: 5

dataset:
  path: "/home/msrai4srl4s/nian/MOLLM/data/goals5.json"

init_datset: ZINC



