exper_name: ""
save_dir: "/home/hp/src/mollm_results/exp"
save_suffix: "0507_exp0.3"
initial_pop: "random1" # best100, worst100, random1 ~ 5

material: False
model:
  name: zhongzhuan,gemini-2.0-flash
  prompt_module: Prompt
  experience_prob: 0.3
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 


goals: [sa,drd2,qed,gsk3b,jnk3]

optimization: 
  pop_size: 50
  eval_budget: 5000
  ngen: 5

dataset:
  path: "/home/hp/src/MOLLM/data/goals5.json"

init_datset: ZINC



