exper_name: "constellaration problem 3"
description: "Multi-objective ideal-MHD stable QI stellarators"
save_dir: "/home/hp/src/mollm_results/fusion"
save_suffix: "0807"
resume: True

model:
  name: zgca,gemini-2.5-flash-nothinking  #,gemini-2.5-flash-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  # name2: zgca,gpt-4o-2024-05-13
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.8
  mutation_prob: 0.2 
  explore_prob: 0. 
use_au: False  # If True, this will use au model, set to false if you only want to use one LLM

goals: [l_delta_b,aspect_ratio]
optimization_direction: [max,min]
prompt_info_path: /home/hp/src/MOLLM/problem/fusion/prompt_info.yaml   
### Important ###
evalutor_path: problem.fusion.evaluator

optimization: 
  pop_size: 50
  eval_budget: 5000

early_stopping: False
inject_per_generation: 5




