
exper_name: "SACS Jacket Optimization - Code Block Generation"
description: "Optimizing SACS structure using direct code block generation by LLM."
save_dir: "./moo_results/"
save_suffix: "sacs_block_gen"

resume: False

model:
  name: zgca,gemini-2.5-flash-nothinking  #,gemini-2.5-flash-nothinking     gpt-4-0125-preview  gpt-4o-2024-05-13
  # name2: zgca,gpt-4o-2024-05-13
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.7
  mutation_prob: 0.3
  explore_prob: 0
use_au: False

# --- Key Problem Definitions ---
goals: [weight, uc, fatigue]
optimization_direction: [min, min, max]

prompt_info_path: ./problem/sacs/sacs.yaml
evalutor_path: problem.sacs.evaluator

sacs:
  project_path: "/mnt/d/wsl_sacs_exchange/demo06_project/Demo06"
  install_path: "C:\\Program Files (x86)\\Bentley\\Engineering\\SACS CONNECT Edition V16 Update 1"
  optimizable_blocks:
    - "GRUP LG1"
    - "GRUP LG2"
    - "GRUP LG3"
    - "GRUP LG4"
    - "GRUP T01"
    - "GRUP T02"
    - "GRUP T03"
    - "PGRUP P01"

optimization:
  pop_size: 40
  eval_budget: 5000
