# config.yaml (Modified)

exper_name: "SACS_Jacket_Expanded_3_Obj_Optimization"
description: "Optimizing SACS jacket structure with an expanded set of members (including I-beams) using a 3-objective approach: weight, max_axial_uc, and max_bending_uc."
save_dir: "./moo_results/"
save_suffix: "sacs_expanded_3_obj"

resume: False

model:
  name: zgca,gemini-2.5-flash-nothinking
  prompt_module: Prompt
  experience_prob: 0.5
  crossover_prob: 0.7
  mutation_prob: 0.3
  explore_prob: 0
use_au: False

# --- 核心变更: 更新优化目标，移除疲劳 ---
goals: [weight, axial_uc_max, bending_uc_max]
optimization_direction: [min, min, min]

prompt_info_path: ./problem/sacs/sacs.yaml
evalutor_path: problem.sacs.evaluator

sacs:
  project_path: "/mnt/d/wsl_sacs_exchange/demo06_project/Demo06"
  install_path: "C:\\Program Files (x86)\\Bentley\\Engineering\\SACS CONNECT Edition V16 Update 1"
  
  # --- 核心变更: 大幅扩展可优化的构件组 ---
  optimizable_blocks:
    # 导管架腿 (Legs)
    - "GRUP LG1"
    - "GRUP LG2"
    - "GRUP LG3"
    - "GRUP LG4"
    - "GRUP LG5"
    - "GRUP LG6"
    - "GRUP LG7"
    # 桩 (Piles)
    - "GRUP PL1"
    - "GRUP PL2"
    - "GRUP PL3"
    - "GRUP PL4"
    # 支撑 (Braces)
    - "GRUP T01"
    - "GRUP T02"
    - "GRUP T03"
    - "GRUP T04"
    - "GRUP T05"
    # 其他管件
    - "GRUP W.B"
    # 新增: 平台工字钢主梁 (I-Beams)
    - "GRUP W01"
    - "GRUP W02"
    # 板单元 (Plate Groups)
    - "PGRUP P01"

optimization:
  pop_size: 40
  eval_budget: 5000
